baseURL = ["http://sweetfeetbyesther.nl/"]

[Params]
    Title = ["Sweet Feet by Esther | "]
    author = ["Joël van der Loo"]
    GitHubUser = ["BioGeekJoey"]
    LanguageCode = ["nl-NL"]
    LanguageName = ["nl"]
    DefaultContentLanguage = ["nl"]